'use client';
import React, { useState, useEffect } from 'react';
import { useRouter, useParams } from 'next/navigation';
import Link from 'next/link';
import { employeeAPI, recruiterAPI } from '@/lib/api';
import { NeoButton, NeoCard } from '@/components/ui/neo';
import { CheckCircle2, XCircle, Loader2, Mail, ArrowRight, RefreshCw } from 'lucide-react';
import { cn } from '@/lib/utils';

export default function VerifyEmailPage() {
  const router = useRouter();
  const { role, token } = useParams();
  const [status, setStatus] = useState('loading'); // loading, success, error
  const [message, setMessage] = useState('');
  const [isResending, setIsResending] = useState(false);
  const [resendStatus, setResendStatus] = useState(null); // null, success, error

  // The role from the URL is expected to be 'employee' (as generated by the backend)
  const isEmployee = role === 'employee';
  const themeColor = isEmployee ? 'bg-neo-yellow' : 'bg-neo-pink';
  const textColor = isEmployee ? 'text-neo-blue' : 'text-neo-pink';

  useEffect(() => {
    const verify = async () => {
      if (!token) {
        setStatus('error');
        setMessage('Verification token is missing.');
        return;
      }

      try {
        if (role === 'employee' || role === 'candidate') {
          const response = await employeeAPI.verifyEmail(token);
          setStatus('success');
          setMessage(response.message);
        } else if (role === 'recruiter') {
          const response = await recruiterAPI.verifyEmail(token);
          setStatus('success');
          setMessage(response.message);
        } else {
          setStatus('error');
          setMessage(`Invalid role: ${role}`);
        }
      } catch (err) {
        setStatus('error');
        setMessage(err.response?.data?.message || 'Invalid or expired verification token.');
      }
    };

    verify();
  }, [token, role]);

  const handleResend = async () => {
    if (isResending) return;
    
    // For resending, we need an email addresses. 
    // Since we don't have it on this verification fail page, we prompt for it.
    const emailToResend = window.prompt('Please enter your email to resend the verification link:');
    
    if (!emailToResend || !emailToResend.includes('@')) {
      if (emailToResend) {
        setMessage('Invalid email address provided.');
        setStatus('error');
      }
      return;
    }

    setIsResending(true);
    setStatus('loading');
    setMessage(`Sending new verification link to ${emailToResend}...`);
    
    try {
      const api = role === 'recruiter' ? recruiterAPI : employeeAPI;
      const response = await api.resendVerification(emailToResend);
      setStatus('success');
      setMessage(response.message);
    } catch (err) {
      console.error('Resend error:', err);
      setStatus('error');
      setMessage(err.response?.data?.message || 'Failed to resend verification link. Please try again.');
    } finally {
      setIsResending(false);
    }
  };

  return (
    <div className="min-h-[calc(100vh-80px)] flex items-center justify-center bg-neo-bg dark:bg-zinc-950 p-4 transition-colors">
      <NeoCard className="w-full max-w-md relative pt-10 overflow-hidden">
        <div className={cn("absolute top-0 left-0 w-full h-2", themeColor)}></div>
        
        <div className="flex flex-col items-center text-center space-y-6">
          {status === 'loading' && (
            <>
              <div className="relative">
                <div className={cn("w-20 h-20 rounded-full border-4 border-dashed animate-spin", isEmployee ? "border-neo-yellow" : "border-neo-pink")}></div>
                <Loader2 className={cn("w-10 h-10 absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 animate-pulse", textColor)} />
              </div>
              <h2 className="text-3xl font-black uppercase dark:text-white">Verifying Email</h2>
              <p className="font-mono text-sm dark:text-gray-400">Please wait while we validate your credentials...</p>
            </>
          )}

          {status === 'success' && (
            <>
              <div className={cn("w-24 h-24 rounded-full flex items-center justify-center shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] dark:shadow-[4px_4px_0px_0px_rgba(255,255,255,0.2)] border-4 border-black dark:border-white", themeColor)}>
                <CheckCircle2 className="w-12 h-12 text-black" />
              </div>
              <div className="space-y-2">
                <h2 className="text-3xl font-black uppercase dark:text-white">Success!</h2>
                <div className="p-4 bg-green-50 dark:bg-green-900/20 border-2 border-green-500 shadow-[4px_4px_0px_0px_rgba(34,197,94,0.3)]">
                  <p className="font-bold text-green-700 dark:text-green-400">{message}</p>
                </div>
              </div>
              <Link href={`/login?mode=${role === 'recruiter' ? 'recruiter' : 'candidate'}`} className="w-full">
                <NeoButton size="lg" className={cn("w-full group", themeColor, "text-black")}>
                  Proceed to Login
                  <ArrowRight className="ml-2 w-5 h-5 group-hover:translate-x-1 transition-transform" />
                </NeoButton>
              </Link>
            </>
          )}

          {status === 'error' && (
            <>
              <div className="w-24 h-24 rounded-full bg-red-500 flex items-center justify-center shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] dark:shadow-[4px_4px_0px_0px_rgba(255,255,255,0.2)] border-4 border-black dark:border-white text-white">
                <XCircle className="w-12 h-12" />
              </div>
              <div className="space-y-2">
                <h2 className="text-3xl font-black uppercase dark:text-white">Verification Failed</h2>
                <div className="p-4 bg-red-50 dark:bg-red-900/20 border-2 border-red-500 shadow-[4px_4px_0px_0px_rgba(239,68,68,0.3)]">
                  <p className="font-bold text-red-700 dark:text-red-400">{message}</p>
                </div>
              </div>
              <div className="w-full flex flex-col gap-3">
                <NeoButton 
                  onClick={() => window.location.reload()} 
                  variant="outline" 
                  className="w-full font-bold border-2"
                  disabled={isResending}
                >
                  <RefreshCw className="mr-2 w-4 h-4" />
                  Try Again
                </NeoButton>
                
                <NeoButton 
                  onClick={handleResend}
                  variant="outline"
                  className="w-full font-bold border-2 border-neo-pink text-neo-pink hover:bg-neo-pink hover:text-white"
                  isLoading={isResending}
                  disabled={isResending}
                >
                  <Mail className="mr-2 w-4 h-4" />
                  {isResending ? 'Resending...' : 'Resend Verification link'}
                </NeoButton>

                <Link href={`/login?mode=${role === 'recruiter' ? 'recruiter' : 'candidate'}`} className="w-full">
                  <NeoButton className="w-full bg-neo-blue text-white" disabled={isResending}>
                    Back to Login
                  </NeoButton>
                </Link>
              </div>
            </>
          )}
        </div>

        <div className="mt-8 pt-6 border-t-2 border-dashed border-gray-200 dark:border-zinc-800 text-center">
          <p className="text-xs font-mono text-gray-500 dark:text-gray-400">
            NeoHire Secure Verification System v1.0
          </p>
        </div>
      </NeoCard>
    </div>
  );
}
